---
- name: Installing of basic packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - python-dev
    - git-core
    - vim

- name: Download projects
  git:
    repo: "https://github.com/esikachev/{{ item }}"
    dest: "/home/{{ username }}/{{ item }}"
  with_items:
    - abc
    - abc-server
    - abc-client
  become: true
  become_user: "{{ username }}"

- name: Install configs
  shell: "cp /home/{{ username }}/abc/.vimrc /home/{{ username }}/.vimrc"
  become: true
  become_user: "{{ username }}"

- name: Generate SSH keys
  user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
